<?php
$apikey="rzp_test_18TxWpftEhFeqn"
?>
<script src="https://code.jquery.com/jquery-3.5.0.js"></script>
<form action="confirm.html" method="POST">
    <script
        src="https://checkout.razorpay.com/v1/checkout.js"
        data-key="<?php echo $apikey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
        data-amount="200000"  // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
        data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
        data-id="order_CgmcjRh9ti2lP7"// Replace with the order_id generated by you in the backend.
        data-buttontext="Pay with Razorpay"
        data-name="RailWell Services"
        data-description="Reservation"
        data-image="https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Indian_Railways.svg/1200px-Indian_Railways.svg.png"
        data-prefill.name="<?php echo $_POST['name'];?>"
        data-prefill.email="<?php echo $_POST['email'];?>"
        data-prefill.contact="<?php echo $_POST['mobile'];?>"
    ></script>
    <input type="hidden" custom="Hidden Element" name="hidden">
    </form>
<style>
    .razorpay-payment-button{
        display:none;
    }
    </style>
<script type=text/javascript>
$(document).ready(function(){
    $('.razorpay-payment-button').click();

});
</script>
</php>